{
 "title": "ebpf",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ebpf_exporter_bio_latency_seconds_bucket, instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\"}, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Exporter disk IO now",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{device=~\"rbd.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{ device}}"
    }
   ]
  },
  {
   "title": "IO write Sizes by device",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(ebpf_exporter_io_size_histogram_bucket{instance=~\"${instance:raw}\", device=~\"${device:raw}\", operation=\"write\"}[$__interval])) by (le,instance,device,operation)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IO latency by device",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"${instance:raw}\", device=~\"${device:raw}\"}[$__interval])) by (le,instance,device)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IO latency by device (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"${instance:raw}\", device=~\"${device:raw}\"}[$__rate_interval])) by (le,operation,device,instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO queue length",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "items" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_queue_depth_issue{instance=~\"${instance:raw}\", device=~\"${device:raw}\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}